# BSL connection profiles — referenced by paths.profile_path in falk_project.yaml
# See https://boringdata.github.io/boring-semantic-layer/

# Default: local DuckDB (used by falk init)
warehouse:
  type: duckdb
  database: data/warehouse.duckdb

# ---------------------------------------------------------------------------
# Alternative backends (uncomment and configure as needed)
# ---------------------------------------------------------------------------

# BigQuery — requires: pip install 'ibis-framework[bigquery]'
# bigquery:
#   type: bigquery
#   project_id: your-gcp-project
#   dataset_id: analytics
#   # Credentials: set GOOGLE_APPLICATION_CREDENTIALS or use default gcloud auth

# Snowflake — requires: pip install 'ibis-framework[snowflake]'
# snowflake:
#   type: snowflake
#   user: your_user
#   password: ${SNOWFLAKE_PASSWORD}  # env var substitution
#   account: your-org-id
#   database: your_database
#   schema: your_schema

# PostgreSQL — requires: pip install 'ibis-framework[postgres]'
# postgres:
#   type: postgres
#   host: localhost
#   port: 5432
#   user: your_user
#   password: ${PG_PASSWORD}
#   database: your_database
